[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Simoninator"]
edition = "2018"

[dependencies]
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"
slice-of-array = "0.2.1"
probability = "0.17.0"
